hsrdp:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  Hsrdp_controller:
    type: hsrdp/Hsrdp
    publish_rate: 50

  # Position Controllers ---------------------------------------
#  joint_position_controller:
#    type: position_controllers/JointPositionController
#    joint: joint1
#    pid: {p: 100.0, i: 0.01, d: 10.0} 
